from typing import Protocol


class BlobStore(Protocol):
    async def put(self, content: bytes) -> str: ...
    async def get(self, sha256: str) -> bytes: ...
    async def exists(self, sha256: str) -> bool: ...
